spring:
  application:
    name: authorizer

  datasource:
    url: jdbc:mariadb://localhost:3306/authorizer_db
    username: authorizer
    password: secret

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect

  web:
    resources:
      static-locations: classpath:/docs/

server:
  servlet:
    context-path: /authorizer/api

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /authorizer-swagger.yaml
