spring:
  application:
    name: authorizer

  datasource:
    url: jdbc:mariadb://localhost:3306/authorizer_db
    username: authorizer
    password: secret

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  servlet:
    context-path: /authorizer/api
